plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:fetch_name:
    - prometheus-instance
  instance-state-name: running
compose:
  ansible_host: private_ip_address
  ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -J ubuntu@{{ lookup('env', 'BASTION_IP') }}"
