---
- name: Restart Prometheus
  systemd:
    name: "{{ prometheus_service_name }}"
    state: restarted
    enabled: yes

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: true
    
- name: Restart Alertmanager
  systemd:
    name: alertmanager
    state: restarted
    enabled: yes

